### ISSUE TITLE
Orders not showing in results

### ISSUE THREAD

**Issue by inventosmateros** [rayrutjes/wc-order-search-admin#113]
I tried to search for a specific order but had no results in the popupbox...
So I pressed enter to perform a "classic" search, but also the order was missing.

Tried searching for the name of the buyer, but nothing.... 

Tried from another computer with different user, and nothing....

Deactivated the plugin, and the search now shows the order!
It is not an "old" purchase.
Also not the first time this happens.

Any idea what might be happening?
Thanks, great plugin!

**Comment by rayrutjes** [comment]
The only thing I can think of is the order having something "special" that makes it skipped by the indexing process somehow.

Any idea of the specificity of the order? I would need to be able to reproduce to suggest a fix.

All orders should be indexed regardless of how old, so that is not a criteria indeed.

Have you checked the PHP logs to check if there weren't some errors?
Have you tried re-indexing everything?
