### ISSUE TITLE
Choose which orders to index in Algolia

### ISSUE THREAD

**Issue by rangevideo** [rayrutjes/wc-order-search-admin#95]
Problem: I have too many old orders which I would like to keep in the database, but avoid indexing with Angolia due to the prohibitive cost( 500$/month!).

Can I use a custom order status to skip Angolia Indexing.

**Comment by rangevideo** [comment]
Sorry, I know this is not an issue, but an enhancement. Not sure how to mark it as such.

**Comment by rayrutjes** [comment]
Hi @rangevideo,

Thanks for suggesting this new feature.

In order to implement this, we would need to introduce some garbage collecting behavior to delete oldest orders.

Ideally, I'd like to keep this plugin as lean as possible, and this seems a little bit out of scope at first glance given users generally want to have access to the whole history.

However, I think doing a custom PHP script that deletes old orders shouldn't be too much work.

Let me know what you think.
